class QS1
{
	tag = "QS1";
	class functions1
	{
		file = "functions1";
		class findWaterLocation {};
		class actionClearInventory {};
		class actionRefuelUAV {};
		class actionUAVSoftware {};
		class addAction {};
		class addActionRescueIntel {};
		class addActionGetIntel {};
		class addActionSurrender {};
		class airDrop {};
		class AOdelete {};
		class AOenemy {};
		class AOdefend {};
		class AOenemy2 {};
		class AOminefield {};
		class casRespawn {};
		class clearPosition {};
		class conditionAirDrop {};
		class conditionClearInventory {};
		class conditionMobileArmory {};
		class conditionRefuelUAV {};
		class conditionUAVSoftware1 {};
		class conditionUH80TurretActionLockL {};
		class conditionUH80TurretActionLockR {};
		class conditionUH80TurretActions {};
		class conditionUH80TurretActionUnlockL {};
		class conditionUH80TurretActionUnlockR {};
		class conditionUH80TurretControl1 {};
		class deleteUnits {};
		class ejectCrew {};
		class enemyCAS {};
		class garrisonFortEAST {};
		class garrisonFortIND {};
		class garrisonFortFIA {};
		class garrisonFortSYN {};
		class loadInventory {};
		class respawnPilot {};
		class rewardPlusHintJet {};
		class removeAction {};
		class removeAction0 {};
		class removeAction1 {};
		class setSkill1 {};
		class setSkill2 {};
		class setSkill3 {};
		class setSkill4 {};
		class PTenemyEAST {};
		class Eventcsat {};
		class SMenemyEAST {};
		class SMenemySYND {};
		class SMenemySYNDintel {};
		class SMenemyEASTintel {};
		class SMenemyIND {};
		class SMenemyFIA {};
		class SMdelete {};
		class SMhintFAIL {};
		class SMhintSUCCESS {};
		class switchMoveMP {};
		class taskAttack {};
		class uh80Turret {};
		class uh80TurretActionCancel {};
		class uh80TurretActions {};
		class uh80TurretControl {};
		class uh80TurretReset {};
		class vMonitor {};
		class vSetup02 {};
		class serverMapTP {};
	};
};
class CHVD1
{
	tag = "CHVD1";
	class functions1
	{
		file = "functions1\CHVD1";
		class onCheckedChanged {};
		class onSliderChange {};
		class onLBSelChanged {};
		class onEBinput {};
		class onEBterrainInput {};
		class selTerrainQuality {};
		class updateTerrain {};
		class updateSettings {};
		class openDialog {};
		class init {postInit = 1;};
	};
};
